### ISSUE TITLE
Managing _secret_auth_.json

### ISSUE THREAD

**Issue by fsmosca** [GauriSP10/streamlit_login_auth_ui#7]
The users info are saved in `_secret_auth_.json`. If you run streamlit app locally there will be no issue accessing that file. What about when you deploy it in streamlit cloud for example? Does that file really is save to a server disk?

I would like to save it to an external database. When the user tries to logged in, I would pull the data from database, check the user log in credential etc. How does `streamlit_login_auth_ui` managed it?

BTW I make an [app](https://gameplay.streamlit.app/) out of this package.

**Comment by ycseong07** [comment]
Hello! It's been a while since this issue was closed, but I'm facing the same problem as you. I've deployed my app using Streamlit Sharing, and I want to reference the elements of secret_auth.json. Have you resolved this issue by any chance?

**Comment by fsmosca** [comment]
I use [deta space](https://deta.space/) to save the data.

They have a [documentation](https://deta.space/docs/en/build/reference/sdk/base) how to save and retrieve data.

For small and dev usage it is free.

**Comment by ycseong07** [comment]
Thanks for the quick response. I'll definitely check that out.

Cheers!
